name: Test Site

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]

jobs:
  test_website:
    runs-on: ubuntu-latest
    name: Test Website
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.2
        with:
          url: "https://jessemcdowell.ca"
          honorRobotExclusions: false
          ignorePatterns: "github,google,cloudflare,linkedin.com/in/jessemcdowell/,nuget,duckdns.org,visualstudio.com,amazon"
          recursiveLinks: true
      - name: Output results
        run: echo "${{steps.link-report.outputs.result}}" >> $GITHUB_OUTPUT
