name: Test Site

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types: [completed]

jobs:
  test_website:
    runs-on: ubuntu-latest
    name: Test Website
    steps:
      - name: Check for broken links
        id: link-report
        uses: celinekurpershoek/link-checker@v1.0.2
        with:
          url: "https://jessemcdowell.ca"
          honorRobotExclusions: false
          ignorePatterns: "github,google,cloudflare,linkedin.com/in/jessemcdowell/,nuget,duckdns.org,visualstudio.com,"
          recursiveLinks: true
      - shell: bash
        run: |
          ${{ steps.link-report.outputs.result }} > link-result.txt
      - name: Upload link report results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: link-results.txt
